### ISSUE TITLE
Error Loading Clients - Failed to load client data: INTERNAL_ERROR

### ISSUE THREAD

**Issue by Hukuma1** [games-on-whales/wolfmanager#39]
After a successful pairing on wolf, I am unable to see any clients in the UI of wolf-manager.

![Image](https://github.com/user-attachments/assets/24cc518b-c23c-45be-a693-08c3409e5dcd)

Version
```
latest
202506.003
```

Error Logs from wolf-manager:
```
ERROR
wolfmanager-ui
Jun 22, 2025, 12:21:03 PM
Failed to get pending requests from /pair/pending endpoint

ERROR
api
Jun 22, 2025, 12:21:03 PM
API Error: Wolf socket not available

ERROR
system
Jun 22, 2025, 12:21:33 PM
Socket not found
```

**Comment by salty2011** [comment]
Hey, thanks for the report.

Couple things.

- Can you provide the compose file you are using
- have you enabled the wolf socket on Wolf? This is required by WolfManager, see [Wolf API](https://games-on-whales.github.io/wolf/stable/dev/api.html)

**Comment by Trasen** [comment]
I run in to this every time i recreate the image, chown-ing the wolf.sock has so far resolved the issue :)

**Comment by Hukuma1** [comment]
```
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/etc/wolf
    volumes:
      - /etc/wolf/:/etc/wolf
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
    device_cgroup_rules:
      - c 13:* rmw
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    network_mode: host
    restart: unless-stopped

  wolfmanager:
    image: ghcr.io/games-on-whales/wolfmanager/wolfmanager:latest
    ports:
      - 3006:3000
    environment:
      - NODE_ENV=production
      # NEXTAUTH_SECRET and ENCRYPTION_KEY are auto-generated on first startup
      # - NEXTAUTH_SECRET=your-secret-here  # Optional: provide your own
      # - ENCRYPTION_KEY=your-32-char-key   # Optional: provide your own
      - NEXTAUTH_URL=http://192.168.1.4:3006
    volumes:
      - /var/run/wolf:/var/run/wolf # Mount Wolf socket
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
      - $CONFIG/wolfmanager:/app/config # Persist config directory
    restart: unless-stopped
```

I believe the only thing I changed was the port since my 3000 was already used.

**Comment by salty2011** [comment]
@Hukuma1 Your wolf instance need to have this env var set 

WOLF_SOCKET_PATH=/var/run/wolf/wolf.sock

This exposes the wolf socket so that WolfManager can mount it.

In your case the path for this var should be 

/etc/wolf/wolf.sock

And in WolfManager you would change the path to

/etc/wolf:/var/run/wolf

That should work

**Comment by Hukuma1** [comment]
Ah thank you! I just tried adding `WOLF_SOCKET_PATH=/var/run/wolf/wolf.sock` but now it seems to crash on startup:

```
wolf-1         | 14:31:12.579911654 INFO  | Starting API server on /var/run/wolf/wolf.sock
wolf-1         | 14:31:12.580095755 ERROR | Unhandled exception: bind: No such file or directory [system:2 at /usr/include/boost/asio/detail/reactive_socket_service.hpp:161:5 in function 'boost::system::error_code boost::asio::detail::reactive_socket_service<Protocol>::bind(implementation_type&, const endpoint_type&, boost::system::error_code&)']
wolf-1         | 14:31:12.580200523 INFO  | Control server started on port: 47999
wolf-1         | XDG_RUNTIME_DIR (/tmp/sockets) is not owned by us (uid 0), but by uid 1000! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
```
Is there a way to set `PUID` and `PGID` (if needed)? I tried to manually put it under environments like I got for some of my other services but it did not work. :/

**Comment by Hukuma1** [comment]
> [@Hukuma1](https://github.com/Hukuma1) Your wolf instance need to have this env var set
> 
> WOLF_SOCKET_PATH=/var/run/wolf/wolf.sock
> 
> This exposes the wolf socket so that WolfManager can mount it.
> 
> In your case the path for this var should be
> 
> /etc/wolf/wolf.sock
> 
> And in WolfManager you would change the path to
> 
> /etc/wolf:/var/run/wolf
> 
> That should work

So this seems to have worked for me to be able to launch them again, but I still see the error in the UI.

Logs:

```
wolfmanager-1  |  ✓ Starting...
wolfmanager-1  | [ENV] Secure keys already available in environment
wolfmanager-1  |  ✓ Ready in 186ms
wolfmanager-1  | Error fetching initial client data: Error: INTERNAL_ERROR
wolfmanager-1  |     at l (/app/.next/server/app/clients/page.js:1:69736)
wolfmanager-1  | Error fetching initial client data: Error: INTERNAL_ERROR
wolfmanager-1  |     at l (/app/.next/server/app/clients/page.js:1:69736)
wolfmanager-1  | Error fetching initial client data: Error: INTERNAL_ERROR
wolfmanager-1  |     at l (/app/.next/server/app/clients/page.js:1:69736)
```

Current compose:

```
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/etc/wolf
      - WOLF_SOCKET_PATH=/etc/wolf/wolf.sock
    volumes:
      - /etc/wolf/:/etc/wolf
      - /tmp/sockets:/tmp/sockets:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
    device_cgroup_rules:
      - c 13:* rmw
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    network_mode: host
    restart: unless-stopped

  wolfmanager:
    image: ghcr.io/games-on-whales/wolfmanager/wolfmanager:latest
    ports:
      - 3006:3000
    environment:
      - NODE_ENV=production
      # NEXTAUTH_SECRET and ENCRYPTION_KEY are auto-generated on first startup
      # - NEXTAUTH_SECRET=your-secret-here  # Optional: provide your own
      # - ENCRYPTION_KEY=your-32-char-key   # Optional: provide your own
      - NEXTAUTH_URL=http://192.168.1.4:3006
    volumes:
      - /etc/wolf:/var/run/wolf # Mount Wolf socket
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
      - $CONFIG/wolfmanager:/app/config # Persist config directory
    restart: unless-stopped
networks: {}
```
